apiVersion: v1
kind: Pod
metadata:
  name: consumer-pod
spec:
  restartPolicy: Never
  containers:
  - name: consumer
    image: extra2000/kafka-pubsub/prodcon
    command: ['npm', 'run', 'consumer']
