apiVersion: v1
kind: Pod
metadata:
  name: producer-pod
spec:
  restartPolicy: Never
  containers:
  - name: producer
    image: extra2000/kafka-pubsub/prodcon
    command: ['npm', 'run', 'producer']
