apiVersion: v1
kind: Pod
metadata:
  name: zeromq-pushpull-pod
spec:
  restartPolicy: Never
  containers:
  - name: producer
    image: extra2000/zeromq-pushpull/pushpull
    command: ['npm', 'run', 'producer']
  - name: worker
    image: extra2000/zeromq-pushpull/pushpull
    command: ['npm', 'run', 'worker']
