apiVersion: v1
kind: Pod
metadata:
  name: webservice-pod
spec:
  restartPolicy: Never
  containers:
  - name: webservice
    image: extra2000/kong-podman/webservice
    ports:
    - containerPort: 8000
      protocol: tcp
