apiVersion: v1
kind: Pod
metadata:
  name: webservice-pod
spec:
  restartPolicy: Never
  containers:
  - name: webservice
    image: localhost/extra2000/webservice
    ports:
    - containerPort: 8000
      protocol: tcp
