apiVersion: v1
kind: Pod
metadata:
  name: subscriber-pod
spec:
  restartPolicy: Never
  containers:
  - name: subscriber
    image: extra2000/redis-pubsub/pubsub
    command: ['npm', 'run', 'subscriber']
